apiVersion: v1
kind: ReplicationController
metadata:
  name: sample-rep-ctl
spec:
  replicas: 4
  selector:
    env: dev
  template:
    metadata:
      name: nginx-template
      labels:
        env: dev
    spec:
      containers:
        - name: nginx-ctn
          image: nginx
          ports:
            - containerPort: 80
