apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      module: signup
  template:
    metadata:
      name: ubn-templ
      labels:
        module: signup
    spec:
      containers:
        - name: ubnctn
          image: ubuntu
          command: ["/bin/bash","-c","while true;do echo from deploy obj ubn container;sleep 5;done"]
